
[ [], [],
  [ "Tier1_Glock19_WAR", "", "", "",
    [ "Tier1_15Rnd_9x19_JHP", 15 ], [], "" ],
  [ "U_mas_can_B_CombatUniform_S_NTOG", [
       [ "ACRE_PRC343", 1 ],
       [ "ACE_fieldDressing", 10 ],
       [ "ACE_epinephrine", 2 ],
       [ "ACE_EarPlugs", 1 ],
       [ "ACE_morphine", 2 ],
       [ "ACE_splint", 1 ],
       [ "ACE_tourniquet", 2 ],
       [ "ACE_CableTie", 2 ],
       [ "ItemAndroid", 1 ],
       [ "ACE_MapTools", 1 ],
       [ "Tier1_15Rnd_9x19_JHP", 2, 15 ]
   ] ],
  [ "V_Rangemaster_belt",
    [[ "ACE_IR_Strobe_Item", 1 ]] ],
  [ "UK3CB_UN_B_B_ASS",
    [ [ "ACE_fieldDressing", 10 ],
      [ "ACE_salineIV_250", 2 ],
      [ "ACE_salineIV_500", 2 ],
      [ "ACE_EntrenchingTool", 1 ],
      [ "ACE_microDAGR", 1 ],
      [ "ACE_SpraypaintGreen", 1 ],
      [ "ACE_SpraypaintRed", 1 ],
      [ "Chemlight_green", 1, 1 ],
      [ "ACE_Chemlight_HiRed", 1, 1 ],
      [ "ACE_Chemlight_IR", 1, 1 ],
      [ "SmokeShellPurple", 1, 1 ],
      [ "SmokeShell", 2, 1 ],
      [ "SmokeShellGreen", 1, 1 ],
      [ "SmokeShellRed", 1, 1 ],
      [ "SmokeShellYellow", 1, 1 ],
      [ "B_IR_Grenade", 1, 1 ] ] ],
  "H_mas_can_Beret_n", "", [ "Rangefinder", "", "", "", [], [], "" ], [ "ItemMap", "ItemGPS", "", "ItemCompass", "ItemWatch", "" ] ]