class CGQC_units_mk1_0_HQ : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "HQ";
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_hq_m4a1", "cgqc_gun_glock19_wood", "cgqc_item_laserdesignator", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_hq_m4a1", "cgqc_gun_glock19_wood", "cgqc_item_laserdesignator", "Put", "Throw"};
    items[] = {"ACRE_PRC343", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask", "ItemcTab", "MRH_FoldedSatcomAntenna", "MRH_TacticalDisplay", "ACRE_PRC77"};
    respawnItems[] = {"ACRE_PRC343", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask", "ItemcTab", "MRH_FoldedSatcomAntenna", "MRH_TacticalDisplay", "ACRE_PRC77"};
    magazines[] = {"ACE_M84", "Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag"};
    respawnMagazines[] = {"ACE_M84", "Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "B_UavTerminal", "NVGoggles_mas_can_hv", "cgqc_item_laserdesignator", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan", "G_mas_can_shemag_gog_l", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "B_UavTerminal", "NVGoggles_mas_can_hv", "cgqc_item_laserdesignator", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan", "G_mas_can_shemag_gog_l", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_0_HQ_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_0_HQ.jpg";
};

class CGQC_units_mk1_0_TeamLeader_Carbine : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "TeamLeader (Carbine)";
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_TL_m4a1", "cgqc_gun_glock19_wood", "cgqc_item_laserdesignator", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_TL_m4a1", "cgqc_gun_glock19_wood", "cgqc_item_laserdesignator", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    magazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "UGL_FlareRed_F", "UGL_FlareRed_F", "UGL_FlareRed_F", "1Rnd_SmokeBlue_Grenade_shell", "1Rnd_SmokeBlue_Grenade_shell", "1Rnd_SmokeBlue_Grenade_shell", "1Rnd_Smoke_Grenade_shell", "1Rnd_Smoke_Grenade_shell", "1Rnd_Smoke_Grenade_shell", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "UGL_FlareRed_F", "UGL_FlareRed_F", "UGL_FlareRed_F", "1Rnd_SmokeBlue_Grenade_shell", "1Rnd_SmokeBlue_Grenade_shell", "1Rnd_SmokeBlue_Grenade_shell", "1Rnd_Smoke_Grenade_shell", "1Rnd_Smoke_Grenade_shell", "1Rnd_Smoke_Grenade_shell", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "B_UavTerminal", "NVGoggles_mas_can_hv", "cgqc_item_laserdesignator", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan", "G_mas_can_wrap_gog_B", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "B_UavTerminal", "NVGoggles_mas_can_hv", "cgqc_item_laserdesignator", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan", "G_mas_can_wrap_gog_B", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_0_TeamLeader_Carbine_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_0_TeamLeader_Carbine.jpg";
};

class CGQC_units_mk1_0_TeamLeader_CQB : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "TeamLeader (CQB)";
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_mk18_gl", "cgqc_gun_glock19_wood", "cgqc_item_laserdesignator", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_mk18_gl", "cgqc_gun_glock19_wood", "cgqc_item_laserdesignator", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    magazines[] = {"HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade", "Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade", "Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "B_UavTerminal", "NVGoggles_mas_can_hv", "cgqc_item_laserdesignator", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan", "G_mas_can_balaM_b", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "B_UavTerminal", "NVGoggles_mas_can_hv", "cgqc_item_laserdesignator", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan", "G_mas_can_balaM_b", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_0_TeamLeader_CQB_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_0_TeamLeader_CQB.jpg";
};

class CGQC_units_mk1_1_Rifleman_Carbine : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "Rifleman (Carbine)";
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_rifleman_m4a1", "cgqc_gun_law_wood", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_rifleman_m4a1", "cgqc_gun_law_wood", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    magazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_lr", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_lr", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_1_Rifleman_Carbine_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_1_Rifleman_Carbine.jpg";
};

class CGQC_units_mk1_1_Rifleman_CQB : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "Rifleman (CQB)";
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_rifleman_mk18", "cgqc_gun_law_wood", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_rifleman_mk18", "cgqc_gun_law_wood", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    magazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_rf", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_rf", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_1_Rifleman_CQB_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_1_Rifleman_CQB.jpg";
};

class CGQC_units_mk1_1_Engineer : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "Engineer";
    canDeactivateMines = 1;
    engineer = 1;
    detectSkill = 31;
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_engineer_m4a1", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_engineer_m4a1", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask", "ToolKit", "ACE_DefusalKit", "ACE_M26_Clacker", "MineDetector"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask", "ToolKit", "ACE_DefusalKit", "ACE_M26_Clacker", "MineDetector"};
    magazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "rhsusf_m112_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhsusf_m112x4_mag", "HandGrenade", "HandGrenade", "rhsusf_mine_m14_mag", "rhsusf_mine_m14_mag", "rhsusf_mine_m14_mag", "rhsusf_mine_m14_mag"};
    respawnMagazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "rhsusf_m112_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhsusf_m112x4_mag", "HandGrenade", "HandGrenade", "rhsusf_mine_m14_mag", "rhsusf_mine_m14_mag", "rhsusf_mine_m14_mag", "rhsusf_mine_m14_mag"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_ar", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_ar", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_1_Engineer_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_1_Engineer.jpg";
};

class CGQC_units_mk1_1_Medic : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "Medic";
    attendant = 1;
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_medic_m4a1", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_medic_m4a1", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask", "ACE_salineIV", "ACE_salineIV", "ACE_salineIV", "ACE_salineIV", "ACE_salineIV", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_splint", "ACE_splint", "ACE_splint", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask", "ACE_salineIV", "ACE_salineIV", "ACE_salineIV", "ACE_salineIV", "ACE_salineIV", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_splint", "ACE_splint", "ACE_splint", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet"};
    magazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade"};
    respawnMagazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1_medic", "cgqc_vest_mk1_tan_rf", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1_medic", "cgqc_vest_mk1_tan_rf", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_1_Medic_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_1_Medic.jpg";
};

class CGQC_units_mk1_2_LMG : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "MG (Light)";
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_mk46", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_mk46", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    magazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "HandGrenade", "HandGrenade", "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote", "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote", "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote", "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote", "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote"};
    respawnMagazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "HandGrenade", "HandGrenade", "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote", "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote", "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote", "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote", "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_ar", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_2_LMG_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_2_LMG.jpg";
};

class CGQC_units_mk1_2_HMG : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "MG (Heavy)";
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_mk48", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_mk48", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    magazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "Tier1_250Rnd_762x51_Belt_M993_AP", "Tier1_100Rnd_762x51_Belt_M993_AP", "rhs_mag_m67", "rhs_mag_m67", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "Tier1_250Rnd_762x51_Belt_M993_AP", "Tier1_250Rnd_762x51_Belt_M993_AP", "HandGrenade", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "Tier1_250Rnd_762x51_Belt_M993_AP", "Tier1_100Rnd_762x51_Belt_M993_AP", "rhs_mag_m67", "rhs_mag_m67", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "Tier1_250Rnd_762x51_Belt_M993_AP", "Tier1_250Rnd_762x51_Belt_M993_AP", "HandGrenade", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_ar", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_ar", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_2_HMG_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_2_HMG.jpg";
};

class CGQC_units_mk1_2_Marksman : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "Marksman (417)";
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_hk417", "cgqc_gun_glock19_wood", "ACE_Vector", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_hk417", "cgqc_gun_glock19_wood", "ACE_Vector", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_RangeCard", "ACE_ATragMX", "ACE_Kestrel4500", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask", "ACE_ATragMX", "ACE_Kestrel4500"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_RangeCard", "ACE_ATragMX", "ACE_Kestrel4500", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask", "ACE_ATragMX", "ACE_Kestrel4500"};
    magazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "HandGrenade", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "HandGrenade", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "HandGrenade", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "HandGrenade", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "B_UavTerminal", "NVGoggles_mas_can_hv", "ACE_Vector", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_lr", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "B_UavTerminal", "NVGoggles_mas_can_hv", "ACE_Vector", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_lr", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_2_Marksman_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_2_Marksman.jpg";
};

class CGQC_units_mk1_2_Sniper : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "Sniper (.50)";
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_m200", "cgqc_gun_glock19_wood", "ACE_Vector", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_m200", "cgqc_gun_glock19_wood", "ACE_Vector", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_RangeCard", "ACE_ATragMX", "ACE_Kestrel4500", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_RangeCard", "ACE_ATragMX", "ACE_Kestrel4500", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    magazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "HandGrenade", "HandGrenade", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "HandGrenade", "HandGrenade", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "7Rnd_408_Mag", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "B_UavTerminal", "NVGoggles_mas_can_hv", "ACE_Vector", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_lr", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "B_UavTerminal", "NVGoggles_mas_can_hv", "ACE_Vector", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_lr", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_2_Sniper_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_2_Sniper.jpg";
};

class CGQC_units_mk1_3_AT_MAAWS : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "AT (MAAWS)";
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_rifleman_mk18", "cgqc_gun_mk1_MAAWS", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_rifleman_mk18", "cgqc_gun_mk1_MAAWS", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    magazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "MRAWS_HEAT_F", "MRAWS_HEAT_F", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "MRAWS_HEAT_F", "MRAWS_HEAT_F", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_lr", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_lr", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_3_AT_MAAWS_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_3_AT_MAAWS.jpg";
};

class CGQC_units_mk1_3_AT_Javelin : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "AT (Javelin)";
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_AT_m4a1", "cgqc_gun_mk1_Javelin", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_AT_m4a1", "cgqc_gun_mk1_Javelin", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC343", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ACE_EarPlugs", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_salineIV_500", "ACE_salineIV_500", "ACE_EntrenchingTool", "G_mas_can_gasmask"};
    magazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "jav_AT_mas_can", "jav_AT_mas_can", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"Tier1_15Rnd_9x19_JHP", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade", "ACE_Chemlight_HiRed", "ACE_Chemlight_IR", "SmokeShell", "SmokeShell", "SmokeShell", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellBlue", "SmokeShellRed", "SmokeShellRed", "SmokeShellRed", "B_IR_Grenade", "rhsusf_m112_mag", "jav_AT_mas_can", "jav_AT_mas_can", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_lr", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_mk1", "cgqc_vest_mk1_tan_lr", "G_mas_can_balaM_T", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_3_AT_Javelin_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_3_AT_Javelin.jpg";
};

class CGQC_units_mk1_4_Tank_Driver : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "Tank Driver";
    uniformClass = "cgqc_uniform_mk1";
    weapons[] = {"cgqc_gun_mk1_mp7", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_mp7", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ToolKit"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR", "ToolKit"};
    magazines[] = {"HandGrenade", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"HandGrenade", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "cgqc_item_rangefinder", "cgqc_helmet_mk1_tank", "cgqc_vest_mk1_pilot", "G_mas_can_balaM_b"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "cgqc_item_rangefinder", "cgqc_helmet_mk1_tank", "cgqc_vest_mk1_pilot", "G_mas_can_balaM_b"};
    backpack = "CGQC_units_mk1_4_Tank_Driver_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_4_Tank_Driver.jpg";
};

class CGQC_units_mk1_4_Pilot_heli : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "Helicopter Pilot";
    engineer = 1;
    uniformClass = "cgqc_uniform_mk1_helipilot";
    weapons[] = {"cgqc_gun_mk1_mp7", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_mp7", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR"};
    magazines[] = {"HandGrenade", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"HandGrenade", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_heli_black", "cgqc_vest_mk1_pilot_black", "G_mas_can_wrap_B", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_heli_black", "cgqc_vest_mk1_pilot_black", "G_mas_can_wrap_B", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_4_Pilot_heli_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_4_Pilot_heli.jpg";
};

class CGQC_units_mk1_4_Pilot_Jet : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "Jet Pilot";
    engineer = 1;
    uniformClass = "cgqc_uniform_mk1_jetpilot";
    weapons[] = {"cgqc_gun_mk1_mp7", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_mp7", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR"};
    magazines[] = {"Tier1_20Rnd_9x19_FMJ", "ACE_M84", "MiniGrenade", "MiniGrenade", "ACE_M84", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"Tier1_20Rnd_9x19_FMJ", "ACE_M84", "MiniGrenade", "MiniGrenade", "ACE_M84", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "cgqc_item_rangefinder", "cgqc_helmet_mk1_jetpilot", "cgqc_vest_mk1_pilot", "G_Combat"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "cgqc_item_rangefinder", "cgqc_helmet_mk1_jetpilot", "cgqc_vest_mk1_pilot", "G_Combat"};
    backpack = "CGQC_units_mk1_4_Pilot_Jet_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_4_Pilot_Jet.jpg";
};

class CGQC_units_mk1_4_crew_heli : cgqc_soldat_moderne
{
    faction = "CGQC";
    editorSubcategory = "EdSubcat_cgqc_mk1";
    side = 1;
    displayName = "Helicopter Crew";
    engineer = 1;
    uniformClass = "cgqc_uniform_mk1_helipilot";
    weapons[] = {"cgqc_gun_mk1_mp7", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    respawnWeapons[] = {"cgqc_gun_mk1_mp7", "cgqc_gun_glock19_wood", "cgqc_item_rangefinder", "Put", "Throw"};
    items[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR"};
    respawnItems[] = {"ItemAndroid", "ItemcTabHCam", "ACRE_PRC152", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_fieldDressing", "ACE_epinephrine", "ACE_epinephrine", "ACE_EarPlugs", "ACE_morphine", "ACE_morphine", "ACE_splint", "ACE_tourniquet", "ACE_tourniquet", "ACE_CableTie", "ACE_CableTie", "ACE_MapTools", "ACE_IR_Strobe_Item", "ACE_microDAGR"};
    magazines[] = {"HandGrenade", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade"};
    respawnMagazines[] = {"HandGrenade", "MiniGrenade", "MiniGrenade", "ACE_M84", "ACE_M84", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "40Rnd_46x30SD_mas_can_mag", "HandGrenade", "HandGrenade", "HandGrenade", "HandGrenade"};
    linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_crew_black", "cgqc_vest_mk1_pilot_black", "G_mas_can_wrap_B", "NVGoggles_mas_can_hv"};
    respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemGPS", "NVGoggles_mas_can_hv", "cgqc_item_rangefinder", "cgqc_helmet_crew_black", "cgqc_vest_mk1_pilot_black", "G_mas_can_wrap_B", "NVGoggles_mas_can_hv"};
    backpack = "CGQC_units_mk1_4_crew_heli_pack";
    editorPreview = "\CGQC_2022\pics\CGQC_units_mk1_4_crew_heli.jpg";
};
