name: CGQC Feature request
description: Demande d'ajout
title: "Ajout: "
labels: ["enhancement", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de remplir ce formulaire!!
  - type: input
    id: contact
    attributes:
      label: Contact
      description: Quel est votre nom?
    validations:
      required: false
  - type: textarea
    id: what-you-need
    attributes:
      label: Que voulez vous ajouter au mod?
      description: Votre suggestion
      placeholder: Donnez le plus d'info possible.
      value: "Votre suggestion"
    validations:
      required: true
