name: CGQC Rapport de problème
description: Quest-ce qui s'est passé?
labels: [bug]
body:
- type: input
    id: contact
    attributes:
      label: Nom du joueur
      description: Qui es-tu?
    validations:
      required: false
- type: textarea
  id: description
  attributes:
    label: Quest-ce qui s'est passé?
  validations:
    required: true
