name: CGQC Bug Report
description: Bug Report
title: "Bug: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de remplir ce formulaire!!
  - type: input
    id: contact
    attributes:
      label: Contact
      description: Quel est votre nom?
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est il passé?
      description: Quel est le bug?
      placeholder: Donnez le plus d'info possible.
      value: "Ça chie!"
    validations:
      required: true
