name: CGQC Rapport de problème
description: Quest-ce qui s'est passé?
labels: [bug]
body:
- type: textarea
  id: user
  attributes:
    label: Nom du joueur:
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Quest-ce qui s'est passé?
  validations:
    required: true
