name: CGQC Rapport de problème
description: Quest-ce qui s'est passé?
labels: [bug]
body:
- type: textarea
  id: description
  attributes:
    label: Quest-ce qui s'est passé?
  validations:
    required: true
    - type: textarea
  id: ident
  attributes:
    label: Qui es-tu?
  validations:
    required: true

