// Loadout flags.
// À mitaine parce que j'tanné;o)
// -----------------------------------------------------------------------------------------------------
cgqc_mk1_loadout_0 addAction ["---- Change de rôle mk1------", ""];
cgqc_mk1_loadout_0 addAction ["- Rifleman - Carbine", "loadouts\mk1_rifleman_carbine.sqf"];
cgqc_mk1_loadout_0 addAction ["- Rifleman - CQB", "loadouts\mk1_rifleman_cqb.sqf"];
cgqc_mk1_loadout_0 addAction ["- Medic", "loadouts\mk1_medic.sqf"];
cgqc_mk1_loadout_0 addAction ["- Engineer", "loadouts\mk1_engineer.sqf"];
cgqc_mk1_loadout_0 addAction ["- HQ", "loadouts\mk1_hq.sqf"];
cgqc_mk1_loadout_0 addAction ["- Team/Squad Leader", "loadouts\mk1_tl.sqf"];
cgqc_mk1_loadout_0 addAction ["- Team/Squad Leader CQB", "loadouts\mk1_tl_cqb.sqf"];
cgqc_mk1_loadout_0 addAction ["- MG (Light)", "loadouts\mk1_lmg.sqf"];
cgqc_mk1_loadout_0 addAction ["- MG (Heavy)", "loadouts\mk1_hmg.sqf"];
cgqc_mk1_loadout_0 addAction ["- Marksman", "loadouts\mk1_marksman.sqf"];
cgqc_mk1_loadout_0 addAction ["- Sniper", "loadouts\mk1_sniper.sqf"];
cgqc_mk1_loadout_0 addAction ["- Anti-Tank (MAAWS)", "loadouts\mk1_at_maaws.sqf"];
cgqc_mk1_loadout_0 addAction ["- Anti-Tank (Javelin)", "loadouts\mk1_at_javelin.sqf"];
cgqc_mk1_loadout_0 addAction ["- Helicopter Pilot", "loadouts\mk1_heli_pilot.sqf"];
cgqc_mk1_loadout_0 addAction ["- Helicopter Crew", "loadouts\mk1_heli_crew.sqf"];
cgqc_mk1_loadout_0 addAction ["- Jet Pilot", "loadouts\mk1_at_jet_pilot.sqf"];
cgqc_mk1_loadout_0 addAction ["- Tank Driver/Crew", "loadouts\mk1_driver_tank.sqf"];
// -----------------------------------------------------------------------------------------------------
cgqc_mk1_loadout_1 addAction ["---- Change de rôle mk1------", ""];
cgqc_mk1_loadout_1 addAction ["- Rifleman - Carbine", "loadouts\mk1_rifleman_carbine.sqf"];
cgqc_mk1_loadout_1 addAction ["- Rifleman - CQB", "loadouts\mk1_rifleman_cqb.sqf"];
cgqc_mk1_loadout_1 addAction ["- Medic", "loadouts\mk1_medic.sqf"];
cgqc_mk1_loadout_1 addAction ["- Engineer", "loadouts\mk1_engineer.sqf"];
cgqc_mk1_loadout_1 addAction ["- HQ", "loadouts\mk1_hq.sqf"];
cgqc_mk1_loadout_1 addAction ["- Team/Squad Leader", "loadouts\mk1_tl.sqf"];
cgqc_mk1_loadout_1 addAction ["- Team/Squad Leader CQB", "loadouts\mk1_tl_cqb.sqf"];
cgqc_mk1_loadout_1 addAction ["- MG (Light)", "loadouts\mk1_lmg.sqf"];
cgqc_mk1_loadout_1 addAction ["- MG (Heavy)", "loadouts\mk1_hmg.sqf"];
cgqc_mk1_loadout_1 addAction ["- Marksman", "loadouts\mk1_marksman.sqf"];
cgqc_mk1_loadout_1 addAction ["- Sniper", "loadouts\mk1_sniper.sqf"];
cgqc_mk1_loadout_1 addAction ["- Anti-Tank (MAAWS)", "loadouts\mk1_at_maaws.sqf"];
cgqc_mk1_loadout_1 addAction ["- Anti-Tank (Javelin)", "loadouts\mk1_at_javelin.sqf"];
cgqc_mk1_loadout_1 addAction ["- Helicopter Pilot", "loadouts\mk1_heli_pilot.sqf"];
cgqc_mk1_loadout_1 addAction ["- Helicopter Crew", "loadouts\mk1_heli_crew.sqf"];
cgqc_mk1_loadout_1 addAction ["- Jet Pilot", "loadouts\mk1_at_jet_pilot.sqf"];
cgqc_mk1_loadout_1 addAction ["- Tank Driver/Crew", "loadouts\mk1_driver_tank.sqf"];
// -----------------------------------------------------------------------------------------------------
cgqc_mk1_loadout_2 addAction ["---- Change de rôle mk1------", ""];
cgqc_mk1_loadout_2 addAction ["- Rifleman - Carbine", "loadouts\mk1_rifleman_carbine.sqf"];
cgqc_mk1_loadout_2 addAction ["- Rifleman - CQB", "loadouts\mk1_rifleman_cqb.sqf"];
cgqc_mk1_loadout_2 addAction ["- Medic", "loadouts\mk1_medic.sqf"];
cgqc_mk1_loadout_2 addAction ["- Engineer", "loadouts\mk1_engineer.sqf"];
cgqc_mk1_loadout_2 addAction ["- HQ", "loadouts\mk1_hq.sqf"];
cgqc_mk1_loadout_2 addAction ["- Team/Squad Leader", "loadouts\mk1_tl.sqf"];
cgqc_mk1_loadout_2 addAction ["- Team/Squad Leader CQB", "loadouts\mk1_tl_cqb.sqf"];
cgqc_mk1_loadout_2 addAction ["- MG (Light)", "loadouts\mk1_lmg.sqf"];
cgqc_mk1_loadout_2 addAction ["- MG (Heavy)", "loadouts\mk1_hmg.sqf"];
cgqc_mk1_loadout_2 addAction ["- Marksman", "loadouts\mk1_marksman.sqf"];
cgqc_mk1_loadout_2 addAction ["- Sniper", "loadouts\mk1_sniper.sqf"];
cgqc_mk1_loadout_2 addAction ["- Anti-Tank (MAAWS)", "loadouts\mk1_at_maaws.sqf"];
cgqc_mk1_loadout_2 addAction ["- Anti-Tank (Javelin)", "loadouts\mk1_at_javelin.sqf"];
cgqc_mk1_loadout_2 addAction ["- Helicopter Pilot", "loadouts\mk1_heli_pilot.sqf"];
cgqc_mk1_loadout_2 addAction ["- Helicopter Crew", "loadouts\mk1_heli_crew.sqf"];
cgqc_mk1_loadout_2 addAction ["- Jet Pilot", "loadouts\mk1_at_jet_pilot.sqf"];
cgqc_mk1_loadout_2 addAction ["- Tank Driver/Crew", "loadouts\mk1_driver_tank.sqf"];
// -----------------------------------------------------------------------------------------------------
cgqc_mk1_loadout_3 addAction ["---- Change de rôle mk1------", ""];
cgqc_mk1_loadout_3 addAction ["- Rifleman - Carbine", "loadouts\mk1_rifleman_carbine.sqf"];
cgqc_mk1_loadout_3 addAction ["- Rifleman - CQB", "loadouts\mk1_rifleman_cqb.sqf"];
cgqc_mk1_loadout_3 addAction ["- Medic", "loadouts\mk1_medic.sqf"];
cgqc_mk1_loadout_3 addAction ["- Engineer", "loadouts\mk1_engineer.sqf"];
cgqc_mk1_loadout_3 addAction ["- HQ", "loadouts\mk1_hq.sqf"];
cgqc_mk1_loadout_3 addAction ["- Team/Squad Leader", "loadouts\mk1_tl.sqf"];
cgqc_mk1_loadout_3 addAction ["- Team/Squad Leader CQB", "loadouts\mk1_tl_cqb.sqf"];
cgqc_mk1_loadout_3 addAction ["- MG (Light)", "loadouts\mk1_lmg.sqf"];
cgqc_mk1_loadout_3 addAction ["- MG (Heavy)", "loadouts\mk1_hmg.sqf"];
cgqc_mk1_loadout_3 addAction ["- Marksman", "loadouts\mk1_marksman.sqf"];
cgqc_mk1_loadout_3 addAction ["- Sniper", "loadouts\mk1_sniper.sqf"];
cgqc_mk1_loadout_3 addAction ["- Anti-Tank (MAAWS)", "loadouts\mk1_at_maaws.sqf"];
cgqc_mk1_loadout_3 addAction ["- Anti-Tank (Javelin)", "loadouts\mk1_at_javelin.sqf"];
cgqc_mk1_loadout_3 addAction ["- Helicopter Pilot", "loadouts\mk1_heli_pilot.sqf"];
cgqc_mk1_loadout_3 addAction ["- Helicopter Crew", "loadouts\mk1_heli_crew.sqf"];
cgqc_mk1_loadout_3 addAction ["- Jet Pilot", "loadouts\mk1_at_jet_pilot.sqf"];
cgqc_mk1_loadout_3 addAction ["- Tank Driver/Crew", "loadouts\mk1_driver_tank.sqf"];
// -----------------------------------------------------------------------------------------------------
cgqc_mk1_loadout_4 addAction ["---- Change de rôle mk1------", ""];
cgqc_mk1_loadout_4 addAction ["- Rifleman - Carbine", "loadouts\mk1_rifleman_carbine.sqf"];
cgqc_mk1_loadout_4 addAction ["- Rifleman - CQB", "loadouts\mk1_rifleman_cqb.sqf"];
cgqc_mk1_loadout_4 addAction ["- Medic", "loadouts\mk1_medic.sqf"];
cgqc_mk1_loadout_4 addAction ["- Engineer", "loadouts\mk1_engineer.sqf"];
cgqc_mk1_loadout_4 addAction ["- HQ", "loadouts\mk1_hq.sqf"];
cgqc_mk1_loadout_4 addAction ["- Team/Squad Leader", "loadouts\mk1_tl.sqf"];
cgqc_mk1_loadout_4 addAction ["- Team/Squad Leader CQB", "loadouts\mk1_tl_cqb.sqf"];
cgqc_mk1_loadout_4 addAction ["- MG (Light)", "loadouts\mk1_lmg.sqf"];
cgqc_mk1_loadout_4 addAction ["- MG (Heavy)", "loadouts\mk1_hmg.sqf"];
cgqc_mk1_loadout_4 addAction ["- Marksman", "loadouts\mk1_marksman.sqf"];
cgqc_mk1_loadout_4 addAction ["- Sniper", "loadouts\mk1_sniper.sqf"];
cgqc_mk1_loadout_4 addAction ["- Anti-Tank (MAAWS)", "loadouts\mk1_at_maaws.sqf"];
cgqc_mk1_loadout_4 addAction ["- Anti-Tank (Javelin)", "loadouts\mk1_at_javelin.sqf"];
cgqc_mk1_loadout_4 addAction ["- Helicopter Pilot", "loadouts\mk1_heli_pilot.sqf"];
cgqc_mk1_loadout_4 addAction ["- Helicopter Crew", "loadouts\mk1_heli_crew.sqf"];
cgqc_mk1_loadout_4 addAction ["- Jet Pilot", "loadouts\mk1_at_jet_pilot.sqf"];
cgqc_mk1_loadout_4 addAction ["- Tank Driver/Crew", "loadouts\mk1_driver_tank.sqf"];
// -----------------------------------------------------------------------------------------------------
cgqc_mk1_loadout_5 addAction ["---- Change de rôle mk1------", ""];
cgqc_mk1_loadout_5 addAction ["- Rifleman - Carbine", "loadouts\mk1_rifleman_carbine.sqf"];
cgqc_mk1_loadout_5 addAction ["- Rifleman - CQB", "loadouts\mk1_rifleman_cqb.sqf"];
cgqc_mk1_loadout_5 addAction ["- Medic", "loadouts\mk1_medic.sqf"];
cgqc_mk1_loadout_5 addAction ["- Engineer", "loadouts\mk1_engineer.sqf"];
cgqc_mk1_loadout_5 addAction ["- HQ", "loadouts\mk1_hq.sqf"];
cgqc_mk1_loadout_5 addAction ["- Team/Squad Leader", "loadouts\mk1_tl.sqf"];
cgqc_mk1_loadout_5 addAction ["- Team/Squad Leader CQB", "loadouts\mk1_tl_cqb.sqf"];
cgqc_mk1_loadout_5 addAction ["- MG (Light)", "loadouts\mk1_lmg.sqf"];
cgqc_mk1_loadout_5 addAction ["- MG (Heavy)", "loadouts\mk1_hmg.sqf"];
cgqc_mk1_loadout_5 addAction ["- Marksman", "loadouts\mk1_marksman.sqf"];
cgqc_mk1_loadout_5 addAction ["- Sniper", "loadouts\mk1_sniper.sqf"];
cgqc_mk1_loadout_5 addAction ["- Anti-Tank (MAAWS)", "loadouts\mk1_at_maaws.sqf"];
cgqc_mk1_loadout_5 addAction ["- Anti-Tank (Javelin)", "loadouts\mk1_at_javelin.sqf"];
cgqc_mk1_loadout_5 addAction ["- Helicopter Pilot", "loadouts\mk1_heli_pilot.sqf"];
cgqc_mk1_loadout_5 addAction ["- Helicopter Crew", "loadouts\mk1_heli_crew.sqf"];
cgqc_mk1_loadout_5 addAction ["- Jet Pilot", "loadouts\mk1_at_jet_pilot.sqf"];
cgqc_mk1_loadout_5 addAction ["- Tank Driver/Crew", "loadouts\mk1_driver_tank.sqf"];
// -----------------------------------------------------------------------------------------------------
cgqc_mk1_loadout_6 addAction ["---- Change de rôle mk1------", ""];
cgqc_mk1_loadout_6 addAction ["- Rifleman - Carbine", "loadouts\mk1_rifleman_carbine.sqf"];
cgqc_mk1_loadout_6 addAction ["- Rifleman - CQB", "loadouts\mk1_rifleman_cqb.sqf"];
cgqc_mk1_loadout_6 addAction ["- Medic", "loadouts\mk1_medic.sqf"];
cgqc_mk1_loadout_6 addAction ["- Engineer", "loadouts\mk1_engineer.sqf"];
cgqc_mk1_loadout_6 addAction ["- HQ", "loadouts\mk1_hq.sqf"];
cgqc_mk1_loadout_6 addAction ["- Team/Squad Leader", "loadouts\mk1_tl.sqf"];
cgqc_mk1_loadout_6 addAction ["- Team/Squad Leader CQB", "loadouts\mk1_tl_cqb.sqf"];
cgqc_mk1_loadout_6 addAction ["- MG (Light)", "loadouts\mk1_lmg.sqf"];
cgqc_mk1_loadout_6 addAction ["- MG (Heavy)", "loadouts\mk1_hmg.sqf"];
cgqc_mk1_loadout_6 addAction ["- Marksman", "loadouts\mk1_marksman.sqf"];
cgqc_mk1_loadout_6 addAction ["- Sniper", "loadouts\mk1_sniper.sqf"];
cgqc_mk1_loadout_6 addAction ["- Anti-Tank (MAAWS)", "loadouts\mk1_at_maaws.sqf"];
cgqc_mk1_loadout_6 addAction ["- Anti-Tank (Javelin)", "loadouts\mk1_at_javelin.sqf"];
cgqc_mk1_loadout_6 addAction ["- Helicopter Pilot", "loadouts\mk1_heli_pilot.sqf"];
cgqc_mk1_loadout_6 addAction ["- Helicopter Crew", "loadouts\mk1_heli_crew.sqf"];
cgqc_mk1_loadout_6 addAction ["- Jet Pilot", "loadouts\mk1_at_jet_pilot.sqf"];
cgqc_mk1_loadout_6 addAction ["- Tank Driver/Crew", "loadouts\mk1_driver_tank.sqf"];
// -----------------------------------------------------------------------------------------------------
cgqc_mk1_loadout_7 addAction ["---- Change de rôle mk1------", ""];
cgqc_mk1_loadout_7 addAction ["- Rifleman - Carbine", "loadouts\mk1_rifleman_carbine.sqf"];
cgqc_mk1_loadout_7 addAction ["- Rifleman - CQB", "loadouts\mk1_rifleman_cqb.sqf"];
cgqc_mk1_loadout_7 addAction ["- Medic", "loadouts\mk1_medic.sqf"];
cgqc_mk1_loadout_7 addAction ["- Engineer", "loadouts\mk1_engineer.sqf"];
cgqc_mk1_loadout_7 addAction ["- HQ", "loadouts\mk1_hq.sqf"];
cgqc_mk1_loadout_7 addAction ["- Team/Squad Leader", "loadouts\mk1_tl.sqf"];
cgqc_mk1_loadout_7 addAction ["- Team/Squad Leader CQB", "loadouts\mk1_tl_cqb.sqf"];
cgqc_mk1_loadout_7 addAction ["- MG (Light)", "loadouts\mk1_lmg.sqf"];
cgqc_mk1_loadout_7 addAction ["- MG (Heavy)", "loadouts\mk1_hmg.sqf"];
cgqc_mk1_loadout_7 addAction ["- Marksman", "loadouts\mk1_marksman.sqf"];
cgqc_mk1_loadout_7 addAction ["- Sniper", "loadouts\mk1_sniper.sqf"];
cgqc_mk1_loadout_7 addAction ["- Anti-Tank (MAAWS)", "loadouts\mk1_at_maaws.sqf"];
cgqc_mk1_loadout_7 addAction ["- Anti-Tank (Javelin)", "loadouts\mk1_at_javelin.sqf"];
cgqc_mk1_loadout_7 addAction ["- Helicopter Pilot", "loadouts\mk1_heli_pilot.sqf"];
cgqc_mk1_loadout_7 addAction ["- Helicopter Crew", "loadouts\mk1_heli_crew.sqf"];
cgqc_mk1_loadout_7 addAction ["- Jet Pilot", "loadouts\mk1_at_jet_pilot.sqf"];
cgqc_mk1_loadout_7 addAction ["- Tank Driver/Crew", "loadouts\mk1_driver_tank.sqf"];
// -----------------------------------------------------------------------------------------------------
cgqc_mk1_loadout_8 addAction ["---- Change de rôle mk1------", ""];
cgqc_mk1_loadout_8 addAction ["- Rifleman - Carbine", "loadouts\mk1_rifleman_carbine.sqf"];
cgqc_mk1_loadout_8 addAction ["- Rifleman - CQB", "loadouts\mk1_rifleman_cqb.sqf"];
cgqc_mk1_loadout_8 addAction ["- Medic", "loadouts\mk1_medic.sqf"];
cgqc_mk1_loadout_8 addAction ["- Engineer", "loadouts\mk1_engineer.sqf"];
cgqc_mk1_loadout_8 addAction ["- HQ", "loadouts\mk1_hq.sqf"];
cgqc_mk1_loadout_8 addAction ["- Team/Squad Leader", "loadouts\mk1_tl.sqf"];
cgqc_mk1_loadout_8 addAction ["- Team/Squad Leader CQB", "loadouts\mk1_tl_cqb.sqf"];
cgqc_mk1_loadout_8 addAction ["- MG (Light)", "loadouts\mk1_lmg.sqf"];
cgqc_mk1_loadout_8 addAction ["- MG (Heavy)", "loadouts\mk1_hmg.sqf"];
cgqc_mk1_loadout_8 addAction ["- Marksman", "loadouts\mk1_marksman.sqf"];
cgqc_mk1_loadout_8 addAction ["- Sniper", "loadouts\mk1_sniper.sqf"];
cgqc_mk1_loadout_8 addAction ["- Anti-Tank (MAAWS)", "loadouts\mk1_at_maaws.sqf"];
cgqc_mk1_loadout_8 addAction ["- Anti-Tank (Javelin)", "loadouts\mk1_at_javelin.sqf"];
cgqc_mk1_loadout_8 addAction ["- Helicopter Pilot", "loadouts\mk1_heli_pilot.sqf"];
cgqc_mk1_loadout_8 addAction ["- Helicopter Crew", "loadouts\mk1_heli_crew.sqf"];
cgqc_mk1_loadout_8 addAction ["- Jet Pilot", "loadouts\mk1_at_jet_pilot.sqf"];
cgqc_mk1_loadout_8 addAction ["- Tank Driver/Crew", "loadouts\mk1_driver_tank.sqf"];
// -----------------------------------------------------------------------------------------------------
cgqc_mk1_loadout_9 addAction ["---- Change de rôle mk1------", ""];
cgqc_mk1_loadout_9 addAction ["- Rifleman - Carbine", "loadouts\mk1_rifleman_carbine.sqf"];
cgqc_mk1_loadout_9 addAction ["- Rifleman - CQB", "loadouts\mk1_rifleman_cqb.sqf"];
cgqc_mk1_loadout_9 addAction ["- Medic", "loadouts\mk1_medic.sqf"];
cgqc_mk1_loadout_9 addAction ["- Engineer", "loadouts\mk1_engineer.sqf"];
cgqc_mk1_loadout_9 addAction ["- HQ", "loadouts\mk1_hq.sqf"];
cgqc_mk1_loadout_9 addAction ["- Team/Squad Leader", "loadouts\mk1_tl.sqf"];
cgqc_mk1_loadout_9 addAction ["- Team/Squad Leader CQB", "loadouts\mk1_tl_cqb.sqf"];
cgqc_mk1_loadout_9 addAction ["- MG (Light)", "loadouts\mk1_lmg.sqf"];
cgqc_mk1_loadout_9 addAction ["- MG (Heavy)", "loadouts\mk1_hmg.sqf"];
cgqc_mk1_loadout_9 addAction ["- Marksman", "loadouts\mk1_marksman.sqf"];
cgqc_mk1_loadout_9 addAction ["- Sniper", "loadouts\mk1_sniper.sqf"];
cgqc_mk1_loadout_9 addAction ["- Anti-Tank (MAAWS)", "loadouts\mk1_at_maaws.sqf"];
cgqc_mk1_loadout_9 addAction ["- Anti-Tank (Javelin)", "loadouts\mk1_at_javelin.sqf"];
cgqc_mk1_loadout_9 addAction ["- Helicopter Pilot", "loadouts\mk1_heli_pilot.sqf"];
cgqc_mk1_loadout_9 addAction ["- Helicopter Crew", "loadouts\mk1_heli_crew.sqf"];
cgqc_mk1_loadout_9 addAction ["- Jet Pilot", "loadouts\mk1_at_jet_pilot.sqf"];
cgqc_mk1_loadout_9 addAction ["- Tank Driver/Crew", "loadouts\mk1_driver_tank.sqf"];